matrix:
  include:
    - language: java
      jdk:
        - openjdk8
      cache:
        directories:
          - "$HOME/.m2/repository"

      install: true
      script: mvn clean package -Drelease
